[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "datacannon"
version = "0.1.0"
requires-python = ">=3.7"
dependencies = [
    "mysql-connector-python",
    "websockets"
]

[project.scripts]
clidb = "src.server.db_cli:main"
datacannon = "src.server.datacannon:main"

